ДЗ 4
AndreiKavunov/KavMtsProj pull request #12
Opened 2021-07-23 05:41 UTC by AndreiKavunov

2021-07-23 14:26 UTC, NikolayUkhvarov requested changes

2021-07-23 14:26 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/OnClickTest.kt
> +interface OnClickTest {
почему тест?

2021-07-23 14:26 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/adapter/CategoryAdapter.kt
> +    class CategoryHolder(item: View):RecyclerView.ViewHolder(item) {
вьюхолдер лучше отдельным классом или точно не в середине другого класса

2021-07-23 14:26 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/adapter/MovieAdapter.kt
> +      holder.itemView.setOnClickListener { view ->
клик можно прокинуть в холдер и там только вызывать
тут точно нужно передавать всю модель?

2021-07-23 14:26 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DTC/Categories.kt
> +data class Categories(val category: String)
в единственном числе

2021-07-23 15:01 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/OnClickTest.kt
> +interface OnClickTest {
Сначала была другая реализация, потом тестил через интерфейс и не поменял название

2021-07-26 17:52 UTC, NikolayUkhvarov requested changes

2021-07-26 17:52 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/goToach.kt
> +interface goToach {
С большой буквы и что-то вроде ClickListener или MovieClickListener

2021-07-27 16:47 UTC, NikolayUkhvarov requested changes
жду исправления по апк

2021-07-28 17:44 UTC, NikolayUkhvarov approved these changes

2021-07-28 19:25 UTC, merged