5 ДЗ версия 3
AndreiKavunov/KavMtsProj pull request #19
Opened 2021-07-28 12:57 UTC by AndreiKavunov

2021-07-28 17:49 UTC, NikolayUkhvarov requested changes

2021-07-28 17:49 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +private const val ARG_PARAM1 = "param1"
почему не компаньон?

2021-07-28 17:49 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +        when(arguments?.getInt(ARG_PARAM1)!!){
это неверно
отображаются не актеры нужного фильма, перенеси список в модель фильма

2021-07-29 14:45 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +        when(arguments?.getInt(ARG_PARAM1)!!){
Говорили, что можно для 3-4 фильмов список сделать, я так и сделал, а в остальные прокинул от первого фильма. Перенес в модель, теперь у каждого свои актеры))

2021-07-29 16:59 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +private const val ARG_PARAM1 = "param1"
Не понял разницы, сделал так, теперь переделал на компаньен обжект

2021-07-29 17:19 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +private const val ARG_PARAM1 = "param1"
лучше придерживаться какого-то одного форматирования
в основном, константы кладем в компаньон
+ без слова const переменная инициализируется после компаньона тк он идет первым

2021-07-29 17:22 UTC, NikolayUkhvarov approved these changes

2021-07-29 17:42 UTC, merged