7 ДЗ
AndreiKavunov/KavMtsProj pull request #21
Opened 2021-08-05 08:29 UTC by AndreiKavunov

2021-08-06 08:50 UTC, NikolayUkhvarov requested changes

2021-08-06 08:50 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +        var listfilm = getMovieAt(position!!.toInt())
не используем !!

2021-08-06 08:50 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +    var list: MutableList<MovieDto> = ArrayList()
для чего этот лист?

2021-08-06 08:50 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +        var listfilm = getMovieAt(position!!.toInt())
это не должно быть во вьюмодели?

2021-08-06 08:50 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
> +        if (movie!=null){
похоже на лишнюю для view логику

2021-08-06 08:50 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
> +        if (isDownloaded) {
это тоже

2021-08-06 15:19 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
> +        if (movie!=null){
Убрал

2021-08-06 15:27 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +    var list: MutableList<MovieDto> = ArrayList()
Не нужен, андроид студия его почему то не затемняла, и я не заметил

2021-08-06 16:55 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +        var listfilm = getMovieAt(position!!.toInt())
Должно, туда и оправил))

2021-08-06 19:33 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
> +        if (isDownloaded) {
Не понял, что тут плохо, но поправил

2021-08-07 15:23 UTC, NikolayUkhvarov requested changes

2021-08-07 15:23 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
> +        adapterCateg.initData(CategoryDataSourceImpl().getMovies())
с дата сорсом должна общаться модель/репозиторий
и уже из вьюмодели доходить до вью

2021-08-09 11:56 UTC, NikolayUkhvarov requested changes

2021-08-09 11:56 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +        CoroutineScope(Dispatchers.Main).launch() {
корутин не должно быть во вью
убери в вьюмодель

2021-08-09 11:56 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
> +            CoroutineScope(Dispatchers.Main).launch() {
снова корутина во вью

2021-08-09 11:56 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
>              job = CoroutineScope(Dispatchers.Main).launch(handler) {
и тут

2021-08-10 11:49 UTC, NikolayUkhvarov approved these changes

2021-08-10 14:26 UTC, merged