8 ДЗ
AndreiKavunov/KavMtsProj pull request #22
Opened 2021-08-12 05:52 UTC by AndreiKavunov

2021-08-12 17:58 UTC, NikolayUkhvarov requested changes

2021-08-12 17:58 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/ProfilFragment.kt
> +    fun viewProf(profilTableModel: ProfilTableModel){
почему эта модель во вью?
тут должна быть другая модель

2021-08-13 06:16 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/ProfilFragment.kt
> +    fun viewProf(profilTableModel: ProfilTableModel){
Создал новую модель, в репозитории перекинул данные в нее из табличной модели, так нужно было сделать?

2021-08-13 12:10 UTC, NikolayUkhvarov requested changes
много именований с 1 и 2 в названии, где-то даже TEST
это тоже нужно убрать и выбрать подходящие названия

2021-08-13 12:10 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +        detailViewModel.loadDetail(position!!.toLong())
без !!

2021-08-13 12:10 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/ProfilFragment.kt
> +        profilViewModel.loadDetail1(1L)
зачем передается id, если он - хардкод?

2021-08-13 12:10 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/repo/DetailRepo.kt
> +        listAct.addAll(listM.getOrNull(0)?.listAct!!)
без !!

2021-08-13 12:10 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/repo/ProfilRepo.kt
> +        listAct.addAll(listM.getOrNull(0)?.listCat!!)
без !!

2021-08-13 12:10 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/viewModel/DetailViewModel.kt
> +            detailRepo = DetailRepo(MovieModel.getMovieID(getApplication(), position)!!, MovieModel.getActorList(getApplication(), position)!!)
без !!
и обращения к MovieModel нужно вынести в репозиторий

2021-08-13 12:10 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/viewModel/ProfilViewModel.kt
> +            profilRepo = ProfilRepo(ProfilModel.getCategList(getApplication(), 1L)!!,
без !!

2021-08-13 12:10 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/viewModel/ProfilViewModel.kt
> +                ProfilModel.getProfilId(getApplication(), id)!!)
без !!

2021-08-13 12:25 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/DetailkFragment.kt
> +        detailViewModel.loadDetail(position!!.toLong())
убрал

2021-08-13 12:28 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/ProfilFragment.kt
> +        profilViewModel.loadDetail1(1L)
На всякий, вдруг нужно будет несколько пользователей заводить. Пока убрал

2021-08-13 12:31 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/repo/DetailRepo.kt
> +        listAct.addAll(listM.getOrNull(0)?.listAct!!)
Убрал

2021-08-13 12:33 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/repo/ProfilRepo.kt
> +        listAct.addAll(listM.getOrNull(0)?.listCat!!)
убрал

2021-08-13 12:46 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/viewModel/DetailViewModel.kt
> +            detailRepo = DetailRepo(MovieModel.getMovieID(getApplication(), position)!!, MovieModel.getActorList(getApplication(), position)!!)
сделал

2021-08-13 12:52 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/viewModel/ProfilViewModel.kt
> +            profilRepo = ProfilRepo(ProfilModel.getCategList(getApplication(), 1L)!!,
убрал

2021-08-13 12:52 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/viewModel/ProfilViewModel.kt
> +                ProfilModel.getProfilId(getApplication(), id)!!)
убрал

2021-08-14 15:19 UTC, NikolayUkhvarov approved these changes

2021-08-18 12:43 UTC, merged