9 ДЗ
AndreiKavunov/KavMtsProj pull request #23
Opened 2021-08-18 12:45 UTC by AndreiKavunov

2021-08-19 22:20 UTC, NikolayUkhvarov requested changes

2021-08-19 22:20 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/movies/MoviesDataSourceImpl.kt
>  		val listFilm = listOf(
для чего остались эти данные?

2021-08-19 22:20 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DTC/MovieDto.kt
> +    val release_date: String,
camelCase

2021-08-19 22:20 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/DTC/MovieDto.kt
> +    val backdrop_path: String,
camelCase

2021-08-19 22:20 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
>  object ListFilm {
не очень понял, что это за объект
архитектурно никуда не вписывается, сделай без него

2021-08-19 22:20 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/MainActivity.kt
> +import okhttp3.*
все эти импорты тут нужны?

2021-08-19 22:20 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/bd/BdModel.kt
> +    val backdrop_path: String,
camelCase

2021-08-19 22:20 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/recponse/respModel/MovieRecpModel.kt
> +class MovieRecpModel {
больше похоже, что это должно быть в дата сорсе
появились лишние классы для работы с сетью, хотя нужно было просто добавить RemoteDataSorce и использовать его вместе с LocalDataSource в репозитории

2021-08-20 07:47 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/movies/MoviesDataSourceImpl.kt
>  		val listFilm = listOf(
Хочу с их помощью проверить 10 дз, сначала загрузил их в базу, приложение работает, потом подгрузились данные с сайта, и все снова работает, но с новыми данными.

2021-08-20 07:48 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/DTC/MovieDto.kt
> +    val release_date: String,
Поправил

2021-08-20 07:48 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/DTC/MovieDto.kt
> +    val backdrop_path: String,
Поправил

2021-08-20 07:50 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/MainActivity.kt
> +import okhttp3.*
Поправил

2021-08-20 07:52 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/bd/BdModel.kt
> +    val backdrop_path: String,
Поправил

2021-08-20 10:39 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/recponse/respModel/MovieRecpModel.kt
> +class MovieRecpModel {
Поправил

2021-08-20 16:07 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/ListFilmFragment.kt
>  object ListFilm {
Убрал

2021-08-23 22:01 UTC, NikolayUkhvarov requested changes

2021-08-23 22:01 UTC, NikolayUkhvarov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/viewModel/MovieViewModel.kt
>      fun startBd(context: Context){
обращения к бд не должно быть в вьюмодели, вынести в репозиторий

2021-08-24 05:57 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/viewModel/MovieViewModel.kt
>      fun startBd(context: Context){
поправил

2021-08-24 06:00 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/repo/MovieRepo.kt
> +            if(listRep != null)for(i in listRep) {
Добавил

2021-08-24 06:13 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/repo/DetailRepo.kt
> +suspend fun getAllAge(idF:String) : String = withContext(Dispatchers.IO){
Убрал

2021-08-24 06:38 UTC, AndreiKavunov commented on app/src/main/java/ru/kavunov/mtsproject/mvvm/repo/DetailRepo.kt
> +suspend fun genreOnId(id: Long): String= withContext(Dispatchers.IO){
В этом классе поправил, дальше буду правильно делать!

2021-08-25 13:30 UTC, NikolayUkhvarov approved these changes

2021-08-25 14:04 UTC, merged